### ISSUE TITLE
no kitty kat?!!!????

### ISSUE THREAD

**Issue by Jul-Wie** [vigow/DotFiles#1]
i dont have kitty cat?? how install!!!?!???? this is so weird omg???!! wtf. giv kitty cat or take down reporsitrory!!!!!!

**Comment by Jul-Wie** [comment]
this is racist to those who dont posses kitty kats!!!!!

**Comment by Jul-Wie** [comment]
stop this!!!!

**Comment by Jul-Wie** [comment]
wait i think i fix!!!!! i print config and put in big cat!!!

**Comment by Jul-Wie** [comment]
nevermind, cat is now cry and no work!!!!

**Comment by Jul-Wie** [comment]
bumb!!!!!

**Comment by vigow** [comment]
install kitty now

**Comment by Jul-Wie** [comment]
WHAT IS A APt!!?!?

**Comment by vigow** [comment]
pacman

**Comment by Jul-Wie** [comment]
i dont play pacman
